### ISSUE TITLE
Issue #06 - Frontend Routes & Components

### ISSUE THREAD

**Issue by keginzburg** [wcorona269/NY-Table#6]
# Frontend Routes
- [X] Frontend routes contains wildcard variables written in `camelCase`
- [X] Correctly formatted
  - [X] Routes are displayed with `inline coding text` (backticks)

## Comments
1. I would use general / path for splash and after a user has logged in? Thoughts?
2. Also, within your /index path, you have Restaurant Theme Components. Do these need Index and Item Components inside? Seems like that’s how OpenTable implements them.
3. Will you need a Photos Component within your RestShow Component?

**Comment by wcorona269** [comment]
Hi Kyle,

I've added the necessary components according to your suggestions. I agree on the first point htat the general '/' path for splash is optimal.

Thank you!
